### ISSUE TITLE
Since we need ground truth 2D-3D matching and self-occlusion results, we provide generation methods in .gdrn_selfocc_modeling/tools. Please refer to generate_*.py. 

### ISSUE THREAD

**Issue by YC0315** [shangbuhuan13/SO-Pose#1]
您好！
    您的工作真的太棒了。
    其次想问下您，“ Please refer to generate_*.py.” 真实的自遮挡坐标需要我们运行什么指令才可以生成吗？还是说在训练的过程中，自己就会生成呢，

**Comment by shangbuhuan13** [comment]
您好，
我们提供了生成自遮挡坐标和2D-3D matching的文件，分别在generate_pbr_Q0_fast.py 和generate_pbr_P_fast.py里面.
注意，直接执行这两个函数就可以产生相应的结果，但是里面有两个路径你需要修改成自己的路径
root_dir = "/data/wanggu/Storage/BOP_DATASETS/lm/train_pbr"
model_dir = "/data/wanggu/Storage/BOP_DATASETS/lm/models"
这两个一个是指向目标数据集的，详见GDR-Net的数据结构，一个是指向object model的。
另外这两个函数执行原理都是将所有三角面片投影回来，所以速度较慢。

**Comment by YC0315** [comment]
您好：
    非常感谢您的回信！
    还想请问下您，对于SO-Pose网络直接回归出的 R 有可能不是正交矩阵吗？如果我们加一个约束使回归得到的R为正交矩阵，请问您感觉对精度有没有提高呢？


| |
Yang
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/29/2021 ***@***.***> wrote：

您好，
我们提供了生成自遮挡坐标和2D-3D matching的文件，分别在generate_pbr_Q0_fast.py 和generate_pbr_P_fast.py里面.
注意，直接执行这两个函数就可以产生相应的结果，但是里面有两个路径你需要修改成自己的路径
root_dir = "/data/wanggu/Storage/BOP_DATASETS/lm/train_pbr"
model_dir = "/data/wanggu/Storage/BOP_DATASETS/lm/models"
这两个一个是指向目标数据集的，详见GDR-Net的数据结构，一个是指向object model的。
另外这两个函数执行原理都是将所有三角面片投影回来，所以速度较慢。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shangbuhuan13** [comment]
您好，我邮件回复您了
