### ISSUE TITLE
缺失lib.egl_renderer

### ISSUE THREAD

**Issue by jiaming3** [shangbuhuan13/SO-Pose#14]
您好，请问作者可以再提供一次lib.egl_renderer吗，其他以前的网盘都过期了，十分感谢。
https://github.com/shangbuhuan13/SO-Pose/blob/b1cfa9c20bfbb0b4ccd1e8c421e392958628aa4f/core/gdrn_selfocc_modeling/tools/lmo/lmo_2_vis_poses.py#:~:text=from%20lib.egl_renderer.egl_renderer_v3%20import%20EGLRenderer

**Comment by shangbuhuan13** [comment]
链接：https://pan.baidu.com/s/1gJ3V_zMrqNBEIm72HxI1nw 
提取码：jfcm 
--来自百度网盘超级会员V4的分享

**Comment by shangbuhuan13** [comment]
Sorry for the late reply. I just returned from my holiday.

**Comment by wangg12** [comment]
@jiaming3 https://github.com/THU-DA-6D-Pose-Group/self6dpp/tree/main/lib/egl_renderer
