### ISSUE TITLE
LINEMOD results

### ISSUE THREAD

**Issue by dkoguciuk** [shangbuhuan13/SO-Pose#17]
Hi @shangbuhuan13 , I have seen [HERE](https://github.com/shangbuhuan13/SO-Pose#trained-models) that you have uploaded the metrics for LMO and YCB-V. Can you also upload the results for LM? 

Best,
D

**Comment by shangbuhuan13** [comment]
Sorry, I didn't preserve the model of LM.

**Comment by dkoguciuk** [comment]
Sure, thanks!
