### ISSUE TITLE
请问在训练过程中，cpu无法跑满怎么办。

### ISSUE THREAD

**Issue by liuicheng123** [shangbuhuan13/SO-Pose#3]
![image](https://user-images.githubusercontent.com/36021763/141131397-988c6502-73ea-45db-8de1-07ffe021410a.png)

如图所示，cpu无法跑满，导致速度很慢，请问这个有解决办法吗。不知道是不是因为你们基于detectron2的问题还是别的。
感谢解答。
我跑了很多天了，设置多个num_workers后，cpu无法跑满，导致我的速度非常慢，这个怎么办呢。是和你们依托detectron有关吗，还是你别的原因，我看你们在代码中，好像是也有遇到相关问题吗

**Comment by shangbuhuan13** [comment]
确实我们在实验中训练的速度也不快，后面也就这样直接训练了。
感觉网络也不是很复杂，可能确实是基于detectron2进行开发时哪里出了问题。
我们在单个GPU上跑一次也需要一个礼拜。

**Comment by liuicheng123** [comment]
> 确实我们在实验中训练的速度也不快，后面也就这样直接训练了。 感觉网络也不是很复杂，可能确实是基于detectron2进行开发时哪里出了问题。 我们在单个GPU上跑一次也需要一个礼拜。

感谢解答。
