### ISSUE TITLE
关于configs/gdrn_selfocc/lm参数设置

### ISSUE THREAD

**Issue by JiayuLL** [shangbuhuan13/SO-Pose#4]
在模型文件GDRN.py中用到了"Q0_DEF_LW"和"HANDLE_SYM"这两个参数，但在configs/gdrn_selfocc/lm 文件夹中的配置文件没有设置这两个参数，请问这两个参数应该设置什么数值？

**Comment by shangbuhuan13** [comment]
抱歉我也有点忘了。而且因为计算资源有限所以我也没办法现在跑一下代码。
正常来说如果用到了这个权重参数的话可以设置为1.0先试一下，大多数权重 都是1.0.
至于第二个参数HANDLE_SYM应该是计算PM loss的时候是否考虑对称性吧。因为我全部代码在实验中都没有考虑对称物体，所以全部设置成FALSE就行了。根据我之前的实验加上去之后也不会有大的变化。
