### ISSUE TITLE
对于real+syn实验的疑问

### ISSUE THREAD

**Issue by wangJK20191** [shangbuhuan13/SO-Pose#5]
作者您好，我对您的工作十分感兴趣，在复现论文的过程中，我发现在lmo数据集实验中，有关于real+syn的实验设置，但是我发现syn数据的生成有很大的随机性，请问您可以分享一下syn数据集吗？十分感谢您！

**Comment by shangbuhuan13** [comment]
数据集是我直接从GDR-Net的作者那边拷贝过来的。
他应该也是随机生成的，所以应该确实会影响到最终训练的结果。
我没有办法分享给你，那个文件太大了，我上传不上去。
建议你直接用pbr的数据训练就是了，效果比自己渲染的要好。
