### ISSUE TITLE
How to evaluate the trained model on YCBV?

### ISSUE THREAD

**Issue by DecaYale** [shangbuhuan13/SO-Pose#6]
Could you provide a brief script to show how to evaluate the trained model on YCBV dataset? I just found it is hard to run the evaluation based on your current descriptions. Thx.

**Comment by shangbuhuan13** [comment]
Sorry for the late reply. I just came back from the holiday.
Can you evaluate the model on LMO.?
I think the evaluation methods are similar on different datasets.
I can't run the model on YCBV now as I have removed the dataset from my computer for space. It' too large.
I think you just need to modify the three parameters specified in the readme.
