### ISSUE TITLE
配置文件中`TRAIN2=("lmo_pbr_train")`是否必要

### ISSUE THREAD

**Issue by flyinghu123** [shangbuhuan13/SO-Pose#7]
您好!
我准备使用`gdrn_selfocc_multistep_40E.py`配置文件复现实验，但是我发现在生成xyz后lm/train_pbr/xyz_crop已经很大，并且准备生成train_pbr/Q0,但是这个我估计要3T的存储空间，所以想问下配置文件中`TRAIN2=("lmo_pbr_train",),`的这个是否必要?

**Comment by shangbuhuan13** [comment]
您好，有必要。这个是BOP 提供的虚拟数据，需要这个数据提升效果来复现ADD的结果。
Q0文件700G左右。
BOP上的结果不需要真实数据，直接使用lmo_pbr_train进行训练

**Comment by flyinghu123** [comment]
好的，谢谢！
