### ISSUE TITLE
How can I inference the results?

### ISSUE THREAD

**Issue by RoyAmoyal** [shangbuhuan13/SO-Pose#8]
Hey, How can I inference the results? (3d boundingbox or pointcloud draw)

**Comment by shangbuhuan13** [comment]
First use the provided model to predict R, and t. then you get the estimation of the bounding box.
We provide some codes in SO-Pose/core/gdrn-selfocc-modeling/tools/my_visualizer.py for visualization.
Also the official BOP_toolkit here https://github.com/thodan/bop_toolkit/blob/master/bop_toolkit_lib/visualization.py will help you. 
For point cloud, you can use scatter in python.  You can also find other advanced tools on github easily

**Comment by shangbuhuan13** [comment]
https://github.com/shangbuhuan13/SO-Pose/blob/b1cfa9c20bfbb0b4ccd1e8c421e392958628aa4f/core/gdrn_selfocc_modeling/tools/lmo/lmo_2_vis_poses.py#:~:text=from%20lib.egl_renderer.egl_renderer_v3%20import%20EGLRenderer
