### ISSUE TITLE
请问在可视化结果时可以提供一下你们的lib.egl_renderer吗，感谢。

### ISSUE THREAD

**Issue by liuicheng123** [shangbuhuan13/SO-Pose#9]
如题目所示，请问作者可否提供下可视化结果时用到的lib.egl_renderer，无比感谢。
https://github.com/shangbuhuan13/SO-Pose/blob/b1cfa9c20bfbb0b4ccd1e8c421e392958628aa4f/core/gdrn_selfocc_modeling/tools/lmo/lmo_2_vis_poses.py#:~:text=from%20lib.egl_renderer.egl_renderer_v3%20import%20EGLRenderer

**Comment by shangbuhuan13** [comment]
好的
链接: https://pan.baidu.com/s/11MU-MYSUSkAef5a76F3Z3Q 提取码: ed3h 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v4的分享

**Comment by liuicheng123** [comment]
> 好的 链接: https://pan.baidu.com/s/11MU-MYSUSkAef5a76F3Z3Q 提取码: ed3h 复制这段内容后打开百度网盘手机App，操作更方便哦 --来自百度网盘超级会员v4的分享

谢谢作者的帮助

**Comment by jiaming3** [comment]
您好，上面网盘也过期了，可以再提供一下吗?感谢!
